### ISSUE TITLE
Can't instal from HA Add-on Store

### ISSUE THREAD

**Issue by gopheridze** [troykelly/hassio-addon-unimus#18]
# Problem/Motivation

Can't install HA addon

## Actual behavior

Failed to install add-on
Can't install ghcr.io/troykelly/unimus/amd64:2.0.10: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2.0.10&fromImage=ghcr.io%2Ftroykelly%2Funimus%2Famd64: Internal Server Error ("name unknown")

**Comment by troykelly** [comment]
Thank you @gopheridze I will have a look

**Comment by troykelly** [comment]
Keep open
